import { readRawBody } from '../http/guard.js';
import { rateLimit, challengeHash } from '../security/rateLimit.js';
import type { VercelRequest, VercelResponse } from '../http/types.js';
import crypto from 'crypto';
import { supabaseAdmin } from '../config/supabase.js';
import { handleAssistantMessage } from '../services/lineAssistant.js';
import type { LineMessage } from '../services/line.js';

export const config = {
  api: {
    bodyParser: false,
  },
};

const LINE_REPLY_URL = 'https://api.line.me/v2/bot/message/reply';


interface LineEvent {
  type: string;
  webhookEventId?: string;
  replyToken?: string;
  source?: { type: string; userId?: string };
  message?: { type: string; text?: string };
}

async function reply(accessToken: string, replyToken: string, messages: LineMessage[]): Promise<void> {
  const res = await fetch(LINE_REPLY_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`,
    },
    signal: AbortSignal.timeout(10000),
    body: JSON.stringify({
      replyToken,
      messages,
    }),
  });
  // LINE rejects an invalid payload (e.g. malformed Flex JSON) with a 4xx and a body explaining
  // why -- silently swallowing that (the previous behavior) means a bad message just never
  // arrives, with nothing in the logs to say why. Log it so that failure mode is visible.
  if (!res.ok) {
    console.error(`line-webhook: LINE reply API returned ${res.status}:`, await res.text());
  }
}

interface NotifSettingsRow {
  lineLinkCode?: string;
  lineLinkCodeExpiresAt?: string;
  [key: string]: unknown;
}

// Matches an incoming message's text against any account's pending link code (generated by
// api/line-link-code.ts from Settings) and links that account's lineUserId on a match --
// self-service, no manual "look up your ID and send it to support" step needed.
async function tryLinkAccount(userId: string, messageText: string): Promise<boolean> {
  const code = messageText.trim().toUpperCase();
  if (!/^[A-F0-9]{16}$/.test(code)) return false;
  await rateLimit('line-claim', userId, 5, 900);
  const result = await supabaseAdmin.rpc('cashflow_claim_line', { p_hash: challengeHash(code), p_line_user_id: userId });
  if (result.error) throw result.error;
  return !!result.data;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const channelSecret = process.env.LINE_CHANNEL_SECRET;
  const accessToken = process.env.LINE_CHANNEL_ACCESS_TOKEN;
  if (!channelSecret || !accessToken) {
    res.status(500).json({ error: 'Missing LINE_CHANNEL_SECRET or LINE_CHANNEL_ACCESS_TOKEN' });
    return;
  }

  const rawBody = await readRawBody(req);
  const signature = req.headers['x-line-signature'];
  const expectedSignature = crypto.createHmac('sha256', channelSecret).update(rawBody).digest('base64');
  if (typeof signature !== 'string' || Buffer.byteLength(signature) !== Buffer.byteLength(expectedSignature) || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expectedSignature))) {
    res.status(401).json({ error: 'Invalid signature' });
    return;
  }

  try {
    const body = JSON.parse(rawBody.toString('utf-8')) as { events?: LineEvent[] };
    const events = body.events || [];

    await Promise.all(
      events.map(async (event) => {
        if (event.type !== 'message' || event.message?.type !== 'text' || !event.replyToken) return;
        const lineUserId = event.source?.userId;
        if (event.source?.type !== 'user' || !lineUserId) return;

        const messageText = (event.message.text || '').slice(0, 5000);
        if (!event.webhookEventId) throw new Error('LINE event is missing its ID');
        const claim = await supabaseAdmin.rpc('cashflow_claim_webhook', { p_key: event.webhookEventId });
        if (claim.error) throw claim.error;
        if (claim.data === 'done') return;
        if (claim.data !== 'claimed') throw new Error('LINE event is still processing');
        await rateLimit('line-message', lineUserId, 30, 60);
        const complete = async () => {
          const result = await supabaseAdmin.from('cashflow_webhook_events').update({ status: 'done' }).eq('key', event.webhookEventId!);
          if (result.error) throw result.error;
        };

        // Already-linked accounts go through the AI assistant (add job / query / report).
        // handleAssistantMessage returns null when this LINE user isn't linked to anything
        // yet, in which case we fall back to matching the message against a pending link code.
        const assistantReply = await handleAssistantMessage(lineUserId, messageText, event.webhookEventId);
        if (assistantReply !== null) {
          await reply(accessToken, event.replyToken, assistantReply);
          await complete();
          return;
        }

        const linked = await tryLinkAccount(lineUserId, messageText);
        const replyText = linked
          ? '✅ เชื่อมต่อบัญชีสำเร็จแล้วครับ!\nตอนนี้คุณจะได้รับแจ้งเตือนจากกระรอกตุนเงินผ่าน LINE นี้ รวมถึงพิมพ์เพิ่มงานหรือถามข้อมูลได้เลยครับ'
          : 'ไม่พบรหัสเชื่อมต่อที่ตรงกันครับ ไปที่หน้าตั้งค่าในแอปกระรอกตุนเงิน > เชื่อมต่อ LINE เพื่อรับรหัสใหม่ แล้วส่งรหัสนั้นมาที่นี่ครับ';

        await reply(accessToken, event.replyToken, [{ type: 'text', text: replyText }]);
        await complete();
      })
    );

    res.status(200).json({ ok: true });
  } catch (err: any) {
    console.error('line-webhook handler error:', err);
    res.status(500).json({ error: 'Webhook handler failed' });
  }
}
